<?php
// $Id$

/**
 * @file
 *  Module installation/uninstallation hooks.
 */

/**
 * Implementation of hook_install().
 */
function location_cck_install() {
}

/**
 * Implementation of hook_uninstall().
 */
function location_cck_uninstall() {
}

/**
 * Implementation of hook_enable().
 */
function location_cck_enable() {
}

/**
 * Implementation of hook_disable().
 */
function location_cck_disable() {
}
